% fitNakaRushton_example

%% Set Parameters

% specify the path to a subject's .mat file task output
path2data="/home/eduwell/SynologyDrive/SNAP/projects/sandbox/pipeCleaner/cleanPrgrmDirsOut/letterFlipper/expDataOut/jnk/jnk_20251013T192221/jnk_20251013T192221.mat";

% specify desired output directory path (this is generated by the script)
dirOut="/home/eduwell/SynologyDrive/SNAP/projects/sandbox/pipeCleaner/cleanPrgrmDirsOut/letterFlipper/nrModelFitOut";

% set the subjID code for the subject whose data is contained in path2data
subjID="JNK";

% set titleStr: this string is added to the plot title for labeling
% purposes and also incorporated into the output figure filename
titleStr="randomString";

% Set Naka Rushton Model Fitting Pars:
%--------------------------------------------------------------------------
NRfitParsIn=struct; % initialize struct
% baseline par "b" upper, lower, bounds, and steps for start grid
NRfitParsIn.nr_bLower=0.25;
NRfitParsIn.nr_bUpper=1;
NRfitParsIn.nr_bSteps=5;
% slope steepness/exponent par "n" upper, lower, bounds, and steps for start grid
NRfitParsIn.nr_n_lower=2;
NRfitParsIn.nr_n_upper=10;
NRfitParsIn.nr_n_steps=5;
% "rmax" upper, lower, bounds, and steps for start grid
NRfitParsIn.nr_rmaxLower=0.25;
NRfitParsIn.nr_rmaxUpper=1;
NRfitParsIn.nr_rmaxSteps=5;
% "c50" upper, lower, bounds, and steps for start grid
NRfitParsIn.c50_lower=5;
NRfitParsIn.c50_upper=75;
NRfitParsIn.c50_steps=5;
% specify accuracy threshold values to solve the best fitting
% functions for at the end..
NRfitParsIn.thrldz2solve=[0.65, 0.75, 0.85];
%--------------------------------------------------------------------------

% Set Pars for analyzeBinnedAccuracy_v6:
%--------------------------------------------------------------------------
correctColNum=10;    % column number for column containing correctness info
accuracyParColNum=3; % column number for column containing the stimulus 
                     % parameter of interest along which you are assessing 
                     % accuracy
parName="TextSize";  % name/label for par in accuracyParColNum
binInfo=struct;      % initialize binning info struct
binInfo.min=5;       % min bin value
binInfo.max=75;      % max bin value
binInfo.nbins=25;    % total desired # of bins from min--> max
binInfo.binThresh=1; % total # of datapoints required for bin inclusion
otherThrPars={};     % Nx2 cell array: {colIdx, requiredValue}; pass [] or {} for none 
                     % these are sets of column index and threshold pairs 
                     % for further selecting a subset of trials with values 
                     % meeting that threshold for the par in that column 
yPltUpperLim=1;      % y plot axis upper limit
yPltLowerLim=0.25;   % y plot axis lower limit
yPltLimz=[yPltUpperLim, yPltLowerLim]; % single vector of containing both 
                                       % the upper and lower y axis limits 
                                       % specified above
%--------------------------------------------------------------------------

%% Load in Data

% load data
dataIn=load(path2data);

% get the tdf array
tdfArray=dataIn.tdfOut;

% separate off the headers
tdfArrayHeaders=tdfArray(1,:);
tdfArray=tdfArray(2:end,:);

% Add/append a subject id column onto end of array as the final column
tdfArray(:,end+1)={subjID};
tdfArrayHeaders(:,end+1)={"subjectID"};

% set subjIDcolNum to the final column
subjIDcolNum=length(tdfArrayHeaders);

subjIDz={subjID};
headerz=tdfArrayHeaders;

%% Run analyzeBinnedAccuracy_v6 to fit Naka-Rushton Model to Data

dataOut = analyzeBinnedAccuracy_v6(dirOut,subjIDz,tdfArray,headerz,subjIDcolNum,correctColNum,accuracyParColNum,parName,binInfo,otherThrPars,titleStr,yPltLimz,NRfitParsIn);
